apiVersion: v1
kind: Service
metadata:
    name: cpallaviiazuredevopsgithubacraksapp
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: cpallaviiazuredevopsgithubacraksapp